Commit
XOLP/go-db-sql-final pull request #1
Opened 2024-11-08 23:42 UTC by XOLP

2024-11-09 10:35 UTC, just-musha requested changes
Привет! Неплохо, функционал есть! Есть что поправить по коду. В первой итерации предалагаю обработать все ошибки, и доработкать все что касается работы с бд - закрытие соединения проверки ошибок.

2024-11-09 10:35 UTC, just-musha commented on .idea/.gitignore
.idea директорию не нужно добавялть в коммит, рекомендую ее в будущем прописать в .gitignore

2024-11-09 10:35 UTC, just-musha commented on main.go
> +	db, err := sql.Open("sqlite", "tracker.db")
Ошибку нужно обработать

2024-11-09 10:35 UTC, just-musha commented on parcel.go
> +	lastId, err := res.LastInsertId()
Обработка ошибки потерялась

2024-11-09 10:35 UTC, just-musha commented on parcel.go
> +		return p, err
Лушче вернуть пустую структуру, в p могут быть битые данные в случае ошибки

2024-11-09 10:35 UTC, just-musha commented on parcel.go
> +	}
После цикла проверить rows.Err нужно не забыть

2024-11-09 10:35 UTC, just-musha commented on parcel.go
> +	}
Нужно закрыть `rows`

2024-11-09 10:35 UTC, just-musha commented on parcel_test.go
> +	db, err := sql.Open("sqlite", "tracker.db") // настройте подключение к БД
Закрыть соединение нужно не забыть

2024-11-09 10:35 UTC, just-musha commented on parcel_test.go
> +	db, err := sql.Open("sqlite", "tracker.db") // настройте подключение к БД
(актуально для всех тестов)

2024-11-10 14:17 UTC, XOLP commented on .idea/.gitignore
Добавил /.idea в gitignore

2024-11-10 14:18 UTC, XOLP commented on main.go
> +	db, err := sql.Open("sqlite", "tracker.db")
Добавил обработку ошибки

2024-11-10 14:18 UTC, XOLP commented on parcel.go
> +	lastId, err := res.LastInsertId()
Добавил обработку ошибки

2024-11-10 14:20 UTC, XOLP commented on parcel.go
> +	}
Закрыл defer rows.Close()

2024-11-10 14:21 UTC, XOLP commented on parcel.go
> +	}
Сделано

2024-11-10 14:22 UTC, XOLP commented on parcel.go
> +		return p, err
Вроде бы верно понял, возвращаю Parcel{}

2024-11-10 14:23 UTC, XOLP commented on parcel_test.go
> +	db, err := sql.Open("sqlite", "tracker.db") // настройте подключение к БД
Добавил закрытие соединения для всех тестов

2024-11-10 16:57 UTC, just-musha approved these changes
Привет! Отлично, все ок по правкам. Принято!

2024-11-10 16:57 UTC, just-musha commented on parcel_test.go
> +	require.Equal(t, parcel.Client, client.Client)
Здесь лучше будет использовать assert - чтобы тест не завершился на первом несовпадении, и можно было сразу увидеть все не совпавшие поля

2024-11-10 18:59 UTC, XOLP commented on parcel_test.go
> +	require.Equal(t, parcel.Client, client.Client)
Понял. Спасибо за правки

2024-11-15 08:37 UTC, merged